//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.CoffeeTables = new HashSet<CoffeeTable>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SalePoint { get; set; }
    
        public virtual SalePoint SalePoint1 { get; set; }
        public virtual ICollection<CoffeeTable> CoffeeTables { get; set; }
    }
}
