//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeTable
    {
        public CoffeeTable()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Orderings = new HashSet<Ordering>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Areas { get; set; }
        public Nullable<bool> IsServe { get; set; }
        public string Notes { get; set; }
        public string OrderNotes { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<Ordering> Orderings { get; set; }
    }
}
