//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportDetail
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<System.DateTime> DateImport { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string UserImport { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
