//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TableID { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Customer { get; set; }
        public string Cashier { get; set; }
        public decimal Total { get; set; }
        public Nullable<double> Discount { get; set; }
        public bool Enable { get; set; }
    
        public virtual CoffeeTable CoffeeTable { get; set; }
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
