//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePoint
    {
        public SalePoint()
        {
            this.Areas = new HashSet<Area>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> RestaurantID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> IsWorking { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
