//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<byte> Role { get; set; }
        public string Position { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateJoin { get; set; }
        public bool Enable { get; set; }
        public string StaffName { get; set; }
    }
}
