//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string UnitImport { get; set; }
        public Nullable<decimal> OriginPrice { get; set; }
        public Nullable<int> QuantityImport { get; set; }
        public Nullable<int> QuantityInStock { get; set; }
        public Nullable<int> QuantitySold { get; set; }
        public Nullable<System.DateTime> LastImport { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
