//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.webapp.Languages.vi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomePageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ff.coffee.webapp.Languages.vi.HomePageResource", typeof(HomePageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách khu vực của điểm bán hàng.
        /// </summary>
        public static string AreaListHeader {
            get {
                return ResourceManager.GetString("AreaListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khu vực.
        /// </summary>
        public static string AreaNameHeader {
            get {
                return ResourceManager.GetString("AreaNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm bán hàng.
        /// </summary>
        public static string AreaSalePointHeader {
            get {
                return ResourceManager.GetString("AreaSalePointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS bàn.
        /// </summary>
        public static string AreaTableListHeader {
            get {
                return ResourceManager.GetString("AreaTableListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm khu vực mới.
        /// </summary>
        public static string ButtonAddNewArea {
            get {
                return ResourceManager.GetString("ButtonAddNewArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bàn mới.
        /// </summary>
        public static string ButtonAddNewCoffeeTbl {
            get {
                return ResourceManager.GetString("ButtonAddNewCoffeeTbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhà hàng mới.
        /// </summary>
        public static string ButtonAddNewRest {
            get {
                return ResourceManager.GetString("ButtonAddNewRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm điểm bán hàng mới.
        /// </summary>
        public static string ButtonAddNewSalePoint {
            get {
                return ResourceManager.GetString("ButtonAddNewSalePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin.
        /// </summary>
        public static string ButtonEditArea {
            get {
                return ResourceManager.GetString("ButtonEditArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin.
        /// </summary>
        public static string ButtonEditRest {
            get {
                return ResourceManager.GetString("ButtonEditRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin.
        /// </summary>
        public static string ButtonEditSalePoint {
            get {
                return ResourceManager.GetString("ButtonEditSalePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bàn của khu vực.
        /// </summary>
        public static string CoffeeTblListHeader {
            get {
                return ResourceManager.GetString("CoffeeTblListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string LoginHeader {
            get {
                return ResourceManager.GetString("LoginHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string LoginUserName {
            get {
                return ResourceManager.GetString("LoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string RestAddressHeader {
            get {
                return ResourceManager.GetString("RestAddressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhà hàng.
        /// </summary>
        public static string RestListHeader {
            get {
                return ResourceManager.GetString("RestListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS điểm bán hàng.
        /// </summary>
        public static string RestListSalePointHeader {
            get {
                return ResourceManager.GetString("RestListSalePointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem danh sách điểm bán hàng.
        /// </summary>
        public static string RestListSalePointLabel {
            get {
                return ResourceManager.GetString("RestListSalePointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà hàng.
        /// </summary>
        public static string RestNameHeader {
            get {
                return ResourceManager.GetString("RestNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string SalePointAddressHeader {
            get {
                return ResourceManager.GetString("SalePointAddressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Khu vực.
        /// </summary>
        public static string SalePointAreaHeader {
            get {
                return ResourceManager.GetString("SalePointAreaHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem danh sách khu vực.
        /// </summary>
        public static string SalePointListAreaLabel {
            get {
                return ResourceManager.GetString("SalePointListAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách điểm bán hàng của nhà hàng.
        /// </summary>
        public static string SalePointListHeader {
            get {
                return ResourceManager.GetString("SalePointListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên điểm bán hàng.
        /// </summary>
        public static string SalePointNameHeader {
            get {
                return ResourceManager.GetString("SalePointNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập hàng.
        /// </summary>
        public static string StoreLandingAddGoodsLabel {
            get {
                return ResourceManager.GetString("StoreLandingAddGoodsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm món.
        /// </summary>
        public static string StoreLandingAddProductsLabel {
            get {
                return ResourceManager.GetString("StoreLandingAddProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục món.
        /// </summary>
        public static string StoreLandingListCatProductLabel {
            get {
                return ResourceManager.GetString("StoreLandingListCatProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Hàng hóa.
        /// </summary>
        public static string StoreLandingListGoodsLabel {
            get {
                return ResourceManager.GetString("StoreLandingListGoodsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Món.
        /// </summary>
        public static string StoreLandingListProductsLabel {
            get {
                return ResourceManager.GetString("StoreLandingListProductsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý bàn.
        /// </summary>
        public static string StoreLandingManageTableLabel {
            get {
                return ResourceManager.GetString("StoreLandingManageTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn.
        /// </summary>
        public static string TableLabel {
            get {
                return ResourceManager.GetString("TableLabel", resourceCulture);
            }
        }
    }
}
