//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.webapp.Languages.vi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ff.coffee.webapp.Languages.vi.MenuResource", typeof(MenuResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        public static string AreasLabel {
            get {
                return ResourceManager.GetString("AreasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển bàn.
        /// </summary>
        public static string ChangeTableLabel {
            get {
                return ResourceManager.GetString("ChangeTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string HomeLabel {
            get {
                return ResourceManager.GetString("HomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Khu vực.
        /// </summary>
        public static string ListAreasLabel {
            get {
                return ResourceManager.GetString("ListAreasLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Loại món.
        /// </summary>
        public static string ListProductCatLabel {
            get {
                return ResourceManager.GetString("ListProductCatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Món.
        /// </summary>
        public static string ListProductLabel {
            get {
                return ResourceManager.GetString("ListProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Nhà hàng.
        /// </summary>
        public static string ListRestaurantLabel {
            get {
                return ResourceManager.GetString("ListRestaurantLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Bàn.
        /// </summary>
        public static string ListTableLabel {
            get {
                return ResourceManager.GetString("ListTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý bàn.
        /// </summary>
        public static string ManageTableLabel {
            get {
                return ResourceManager.GetString("ManageTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS Người dùng.
        /// </summary>
        public static string ManageUserLabel {
            get {
                return ResourceManager.GetString("ManageUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MenuLabel {
            get {
                return ResourceManager.GetString("MenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐK người dùng.
        /// </summary>
        public static string RegisterUserLabel {
            get {
                return ResourceManager.GetString("RegisterUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo kết quả kinh doanh.
        /// </summary>
        public static string ReportIncomeStatementLabel {
            get {
                return ResourceManager.GetString("ReportIncomeStatementLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        public static string ReportLabel {
            get {
                return ResourceManager.GetString("ReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo doanh số.
        /// </summary>
        public static string ReportSalesLabel {
            get {
                return ResourceManager.GetString("ReportSalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm bán hàng.
        /// </summary>
        public static string SalePointLabel {
            get {
                return ResourceManager.GetString("SalePointLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho hàng.
        /// </summary>
        public static string StorageLabel {
            get {
                return ResourceManager.GetString("StorageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string UserLabel {
            get {
                return ResourceManager.GetString("UserLabel", resourceCulture);
            }
        }
    }
}
