//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.webapp.Languages.vi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ff.coffee.webapp.Languages.vi.OrderPageResource", typeof(OrderPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi order.
        /// </summary>
        public static string ButtonSaveOrder {
            get {
                return ResourceManager.GetString("ButtonSaveOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ghi chú.
        /// </summary>
        public static string ButtonSaveOrderNotes {
            get {
                return ResourceManager.GetString("ButtonSaveOrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi thêm.
        /// </summary>
        public static string OrderChangeQuantity {
            get {
                return ResourceManager.GetString("OrderChangeQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn danh mục.
        /// </summary>
        public static string OrderChooseCat {
            get {
                return ResourceManager.GetString("OrderChooseCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        public static string OrderCostlabel {
            get {
                return ResourceManager.GetString("OrderCostlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá (%).
        /// </summary>
        public static string OrderDiscountLabel {
            get {
                return ResourceManager.GetString("OrderDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các món đã gọi.
        /// </summary>
        public static string OrderedListHeader {
            get {
                return ResourceManager.GetString("OrderedListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các món đang thêm.
        /// </summary>
        public static string OrderingListHeader {
            get {
                return ResourceManager.GetString("OrderingListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string OrderNotesLabel {
            get {
                return ResourceManager.GetString("OrderNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string OrderPriceLabel {
            get {
                return ResourceManager.GetString("OrderPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món.
        /// </summary>
        public static string OrderProductLabel {
            get {
                return ResourceManager.GetString("OrderProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string OrderQuantityLabel {
            get {
                return ResourceManager.GetString("OrderQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm món.
        /// </summary>
        public static string OrderSearchProduct {
            get {
                return ResourceManager.GetString("OrderSearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại món.
        /// </summary>
        public static string OrderSearchProductCat {
            get {
                return ResourceManager.GetString("OrderSearchProductCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi thêm món.
        /// </summary>
        public static string OrderSelectProductLabel {
            get {
                return ResourceManager.GetString("OrderSelectProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xác nhận.
        /// </summary>
        public static string OrderStatusConfirm {
            get {
                return ResourceManager.GetString("OrderStatusConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất.
        /// </summary>
        public static string OrderStatusDone {
            get {
                return ResourceManager.GetString("OrderStatusDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string OrderStatusLabel {
            get {
                return ResourceManager.GetString("OrderStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác nhận.
        /// </summary>
        public static string OrderStatusNotConfirm {
            get {
                return ResourceManager.GetString("OrderStatusNotConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn.
        /// </summary>
        public static string OrderTableLabel {
            get {
                return ResourceManager.GetString("OrderTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú bàn.
        /// </summary>
        public static string OrderTableNotesLabel {
            get {
                return ResourceManager.GetString("OrderTableNotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string OrderTimeLabel {
            get {
                return ResourceManager.GetString("OrderTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string OrderTotalLabel {
            get {
                return ResourceManager.GetString("OrderTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string OrderUnitLabel {
            get {
                return ResourceManager.GetString("OrderUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu ngân:.
        /// </summary>
        public static string PayCashierLabel {
            get {
                return ResourceManager.GetString("PayCashierLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.Tiền.
        /// </summary>
        public static string PayCostLabel {
            get {
                return ResourceManager.GetString("PayCostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CK (%).
        /// </summary>
        public static string PayDiscountLabel {
            get {
                return ResourceManager.GetString("PayDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại:.
        /// </summary>
        public static string PayPhoneLabel {
            get {
                return ResourceManager.GetString("PayPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL.
        /// </summary>
        public static string PayQuantityLabel {
            get {
                return ResourceManager.GetString("PayQuantityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán bàn.
        /// </summary>
        public static string PayTableButton {
            get {
                return ResourceManager.GetString("PayTableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn:.
        /// </summary>
        public static string PayTableLabel {
            get {
                return ResourceManager.GetString("PayTableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn Quý khách, hẹn gặp lại!.
        /// </summary>
        public static string PayThanksLabel {
            get {
                return ResourceManager.GetString("PayThanksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian:.
        /// </summary>
        public static string PayTimeLabel {
            get {
                return ResourceManager.GetString("PayTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu tính tiền.
        /// </summary>
        public static string PayTitle {
            get {
                return ResourceManager.GetString("PayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In hóa đơn.
        /// </summary>
        public static string PrintInvoice {
            get {
                return ResourceManager.GetString("PrintInvoice", resourceCulture);
            }
        }
    }
}
