//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.webapp.Languages.vi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ff.coffee.webapp.Languages.vi.ReportPageResource", typeof(ReportPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string ButtonReportDetailHeader {
            get {
                return ResourceManager.GetString("ButtonReportDetailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem báo cáo.
        /// </summary>
        public static string ReportButtonView {
            get {
                return ResourceManager.GetString("ReportButtonView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string ReportDateFromLabel {
            get {
                return ResourceManager.GetString("ReportDateFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đến.
        /// </summary>
        public static string ReportDateToLabel {
            get {
                return ResourceManager.GetString("ReportDateToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu ngân.
        /// </summary>
        public static string ReportSalesCashierHeader {
            get {
                return ResourceManager.GetString("ReportSalesCashierHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh số.
        /// </summary>
        public static string ReportSalesCostHeader {
            get {
                return ResourceManager.GetString("ReportSalesCostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string ReportSalesDateHeader {
            get {
                return ResourceManager.GetString("ReportSalesDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết hóa đơn.
        /// </summary>
        public static string ReportSalesDetail {
            get {
                return ResourceManager.GetString("ReportSalesDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết hóa đơn.
        /// </summary>
        public static string ReportSalesDetailHeader {
            get {
                return ResourceManager.GetString("ReportSalesDetailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảm giá (%).
        /// </summary>
        public static string ReportSalesDiscountHeader {
            get {
                return ResourceManager.GetString("ReportSalesDiscountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo doanh số.
        /// </summary>
        public static string ReportSalesHeader {
            get {
                return ResourceManager.GetString("ReportSalesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bàn.
        /// </summary>
        public static string ReportSalesTableHeader {
            get {
                return ResourceManager.GetString("ReportSalesTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng doanh số.
        /// </summary>
        public static string ReportSalesTotalLabel {
            get {
                return ResourceManager.GetString("ReportSalesTotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành tiền.
        /// </summary>
        public static string SalesDetailCostHeader {
            get {
                return ResourceManager.GetString("SalesDetailCostHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string SalesDetailPriceHeader {
            get {
                return ResourceManager.GetString("SalesDetailPriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Món.
        /// </summary>
        public static string SalesDetailProductHeader {
            get {
                return ResourceManager.GetString("SalesDetailProductHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string SalesDetailQuantityHeader {
            get {
                return ResourceManager.GetString("SalesDetailQuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên Order.
        /// </summary>
        public static string SalesDetailStaffHeader {
            get {
                return ResourceManager.GetString("SalesDetailStaffHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string SalesDetailTotalHeader {
            get {
                return ResourceManager.GetString("SalesDetailTotalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string SalesDetailUnitHeader {
            get {
                return ResourceManager.GetString("SalesDetailUnitHeader", resourceCulture);
            }
        }
    }
}
