//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.webapp.Languages.vi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ff.coffee.webapp.Languages.vi.SettingPageResource", typeof(SettingPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ *.
        /// </summary>
        public static string SettingAddressLabel {
            get {
                return ResourceManager.GetString("SettingAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa khu vực.
        /// </summary>
        public static string SettingAreaDeleteButton {
            get {
                return ResourceManager.GetString("SettingAreaDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin khu vực.
        /// </summary>
        public static string SettingAreaEditHeader {
            get {
                return ResourceManager.GetString("SettingAreaEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khu vực *.
        /// </summary>
        public static string SettingAreaNameLabel {
            get {
                return ResourceManager.GetString("SettingAreaNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm bán hàng *.
        /// </summary>
        public static string SettingAreaSaleLabel {
            get {
                return ResourceManager.GetString("SettingAreaSaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bàn mới.
        /// </summary>
        public static string SettingCoffeeTblAddHeader {
            get {
                return ResourceManager.GetString("SettingCoffeeTblAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa bàn.
        /// </summary>
        public static string SettingCoffeeTblDeleteButton {
            get {
                return ResourceManager.GetString("SettingCoffeeTblDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        public static string SettingCoffeeTblEAreaLabel {
            get {
                return ResourceManager.GetString("SettingCoffeeTblEAreaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin bàn.
        /// </summary>
        public static string SettingCoffeeTblEditHeader {
            get {
                return ResourceManager.GetString("SettingCoffeeTblEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bàn.
        /// </summary>
        public static string SettingCoffeeTblNameLabel {
            get {
                return ResourceManager.GetString("SettingCoffeeTblNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string SettingCoffeeTblNoteLabel {
            get {
                return ResourceManager.GetString("SettingCoffeeTblNoteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SettingEmailLabel {
            get {
                return ResourceManager.GetString("SettingEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax *.
        /// </summary>
        public static string SettingFaxLabel {
            get {
                return ResourceManager.GetString("SettingFaxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại *.
        /// </summary>
        public static string SettingPhoneLabel {
            get {
                return ResourceManager.GetString("SettingPhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhà hàng mới.
        /// </summary>
        public static string SettingRestAddHeader {
            get {
                return ResourceManager.GetString("SettingRestAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa nhà hàng.
        /// </summary>
        public static string SettingRestDeleteButton {
            get {
                return ResourceManager.GetString("SettingRestDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin nhà hàng.
        /// </summary>
        public static string SettingRestEditHeader {
            get {
                return ResourceManager.GetString("SettingRestEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà hàng *.
        /// </summary>
        public static string SettingRestNameLabel {
            get {
                return ResourceManager.GetString("SettingRestNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà hàng không được trống.
        /// </summary>
        public static string SettingRestNameRequired {
            get {
                return ResourceManager.GetString("SettingRestNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khổ giấy *.
        /// </summary>
        public static string SettingRestPrintSizeLabel {
            get {
                return ResourceManager.GetString("SettingRestPrintSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm điểm bán hàng.
        /// </summary>
        public static string SettingSaleAddHeader {
            get {
                return ResourceManager.GetString("SettingSaleAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá điểm bán hàng.
        /// </summary>
        public static string SettingSaleDeleteButton {
            get {
                return ResourceManager.GetString("SettingSaleDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin điểm bán hàng.
        /// </summary>
        public static string SettingSaleEditHeader {
            get {
                return ResourceManager.GetString("SettingSaleEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên điểm bán hàng.
        /// </summary>
        public static string SettingSaleNameLabel {
            get {
                return ResourceManager.GetString("SettingSaleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà hàng *.
        /// </summary>
        public static string SettingSaleRestLabel {
            get {
                return ResourceManager.GetString("SettingSaleRestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string SettingSaveButton {
            get {
                return ResourceManager.GetString("SettingSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string SettingWebsiteLabel {
            get {
                return ResourceManager.GetString("SettingWebsiteLabel", resourceCulture);
            }
        }
    }
}
