//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ff.coffee.webapp.Languages.vi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StorePageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StorePageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ff.coffee.webapp.Languages.vi.StorePageResource", typeof(StorePageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm hàng vào kho.
        /// </summary>
        public static string ButtonAddNewGoods {
            get {
                return ResourceManager.GetString("ButtonAddNewGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm món mới.
        /// </summary>
        public static string ButtonAddNewProduct {
            get {
                return ResourceManager.GetString("ButtonAddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm danh mục.
        /// </summary>
        public static string ButtonAddNewProductCat {
            get {
                return ResourceManager.GetString("ButtonAddNewProductCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm bàn mới.
        /// </summary>
        public static string ButtonAddNewTable {
            get {
                return ResourceManager.GetString("ButtonAddNewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string ButtonEditGoods {
            get {
                return ResourceManager.GetString("ButtonEditGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa món.
        /// </summary>
        public static string ButtonEditProduct {
            get {
                return ResourceManager.GetString("ButtonEditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string ButtonEditProductCat {
            get {
                return ResourceManager.GetString("ButtonEditProductCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin bàn.
        /// </summary>
        public static string ButtonEditTable {
            get {
                return ResourceManager.GetString("ButtonEditTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập hàng.
        /// </summary>
        public static string GoodsAddHeader {
            get {
                return ResourceManager.GetString("GoodsAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhập.
        /// </summary>
        public static string GoodsImportPriceHeader {
            get {
                return ResourceManager.GetString("GoodsImportPriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL nhập.
        /// </summary>
        public static string GoodsImportQuantityHeader {
            get {
                return ResourceManager.GetString("GoodsImportQuantityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nhập cuối.
        /// </summary>
        public static string GoodsLastImportHeader {
            get {
                return ResourceManager.GetString("GoodsLastImportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách hàng trong kho.
        /// </summary>
        public static string GoodsListHeader {
            get {
                return ResourceManager.GetString("GoodsListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng hóa.
        /// </summary>
        public static string GoodsNameHeader {
            get {
                return ResourceManager.GetString("GoodsNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng.
        /// </summary>
        public static string GoodsNameLabel {
            get {
                return ResourceManager.GetString("GoodsNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhập.
        /// </summary>
        public static string GoodsOriginPriceLabel {
            get {
                return ResourceManager.GetString("GoodsOriginPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhập.
        /// </summary>
        public static string GoodsQuantityImportLabel {
            get {
                return ResourceManager.GetString("GoodsQuantityImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL tồn.
        /// </summary>
        public static string GoodsQuantityInStockHeader {
            get {
                return ResourceManager.GetString("GoodsQuantityInStockHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL bán được.
        /// </summary>
        public static string GoodsQuantitySoldHeader {
            get {
                return ResourceManager.GetString("GoodsQuantitySoldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string GoodsUnitHeader {
            get {
                return ResourceManager.GetString("GoodsUnitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string GoodsUnitLabel {
            get {
                return ResourceManager.GetString("GoodsUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm món.
        /// </summary>
        public static string ProductAddHeader {
            get {
                return ResourceManager.GetString("ProductAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục mới.
        /// </summary>
        public static string ProductCatAddHeader {
            get {
                return ResourceManager.GetString("ProductCatAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string ProductCatDescHeader {
            get {
                return ResourceManager.GetString("ProductCatDescHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string ProductCatDescLabel {
            get {
                return ResourceManager.GetString("ProductCatDescLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string ProductCatHeader {
            get {
                return ResourceManager.GetString("ProductCatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string ProductCatLabel {
            get {
                return ResourceManager.GetString("ProductCatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS danh mục.
        /// </summary>
        public static string ProductCatListHeader {
            get {
                return ResourceManager.GetString("ProductCatListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string ProductCatNameHeader {
            get {
                return ResourceManager.GetString("ProductCatNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string ProductCatNameLabel {
            get {
                return ResourceManager.GetString("ProductCatNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        public static string ProductDateCreateHeader {
            get {
                return ResourceManager.GetString("ProductDateCreateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thông tin món.
        /// </summary>
        public static string ProductEditHeader {
            get {
                return ResourceManager.GetString("ProductEditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách món.
        /// </summary>
        public static string ProductListHeader {
            get {
                return ResourceManager.GetString("ProductListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món.
        /// </summary>
        public static string ProductNameHeader {
            get {
                return ResourceManager.GetString("ProductNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món.
        /// </summary>
        public static string ProductNameLabel {
            get {
                return ResourceManager.GetString("ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string ProductPriceHeader {
            get {
                return ResourceManager.GetString("ProductPriceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn giá.
        /// </summary>
        public static string ProductPriceLabel {
            get {
                return ResourceManager.GetString("ProductPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string ProductUnitHeader {
            get {
                return ResourceManager.GetString("ProductUnitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string ProductUnitLabel {
            get {
                return ResourceManager.GetString("ProductUnitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá danh mục.
        /// </summary>
        public static string StoreProdcutCatDeleteButton {
            get {
                return ResourceManager.GetString("StoreProdcutCatDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa món.
        /// </summary>
        public static string StoreProdcutDisableButton {
            get {
                return ResourceManager.GetString("StoreProdcutDisableButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string StoreSaveButton {
            get {
                return ResourceManager.GetString("StoreSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khu vực.
        /// </summary>
        public static string TableAreaUnitHeader {
            get {
                return ResourceManager.GetString("TableAreaUnitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bàn.
        /// </summary>
        public static string TableListHeader {
            get {
                return ResourceManager.GetString("TableListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bàn.
        /// </summary>
        public static string TableNameHeader {
            get {
                return ResourceManager.GetString("TableNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string TableNotesHeader {
            get {
                return ResourceManager.GetString("TableNotesHeader", resourceCulture);
            }
        }
    }
}
